### Consigna: Si decimos que la ubicación de una categoría es el promedio de la latitud y longitud de sus contenidos geolocalizados que son miembros de ella (si es que tiene): ¿Cuales son las dos categorías más cercanas? (⭐⭐⭐)

Importo la libreria que utilizaré para realizar el ejercicio.

In [16]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import numpy as np

In [17]:
arcGeo = pd.read_csv('geo_tags.csv',\
                 usecols =['gt_lat','gt_lon','gt_page_id'])
arcGeo

gt_page_id     gt_lat     gt_lon
0          4328020  41.507500  -5.817500
1          4670424  13.738000 -89.292000
2          4670424  13.702000 -89.208000
3          4670424  13.400000 -89.750000
4          4670424  12.850000 -88.000000
...            ...        ...        ...
556388     5239183   3.450000 -76.533333
556389      104468  30.815839  45.996069
556390      968281  46.953333   6.256944
556391       79985  45.109659   7.641221
556392      872296  15.425675 -90.326285

[556393 rows x 3 columns]

In [18]:
#renombro la columna ya que me resulta necesario para luego poder hacer el merge
arcGeo.rename(columns={'gt_page_id':'id'},inplace=True)
arcGeo

id     gt_lat     gt_lon
0       4328020  41.507500  -5.817500
1       4670424  13.738000 -89.292000
2       4670424  13.702000 -89.208000
3       4670424  13.400000 -89.750000
4       4670424  12.850000 -88.000000
...         ...        ...        ...
556388  5239183   3.450000 -76.533333
556389   104468  30.815839  45.996069
556390   968281  46.953333   6.256944
556391    79985  45.109659   7.641221
556392   872296  15.425675 -90.326285

[556393 rows x 3 columns]

In [19]:
arcCat = pd.read_csv('categorylinks.csv',\
                 usecols= ['cl_from','cl_to'])
arcCat

cl_from                                              cl_to
0                5                            Wikipedia:Mantenimiento
1                5    Wikipedia:Páginas_con_enlaces_mágicos_de_ISBN
2                7                                            Andorra
3                7  Instituciones_patrocinadoras_de_equipos_ciclistas
4                7             Wikipedia:Artículos_con_datos_locales
...            ...                                                ...
13308614  10010781                                    Nacidos_en_1994
13308615  10010781                                     Personas_vivas
13308616  10010783                          Fundaciones_en_Sudáfrica
13308617  10010787                 Fundaciones_en_Sudáfrica_por_año
13308618  10010787                                 Sudáfrica_en_2010

[13308619 rows x 2 columns]

In [20]:
arcCat.rename(columns={'cl_from':'id','cl_to':'categoria'},inplace=True)
arcCat

id                                          categoria
0                5                            Wikipedia:Mantenimiento
1                5    Wikipedia:Páginas_con_enlaces_mágicos_de_ISBN
2                7                                            Andorra
3                7  Instituciones_patrocinadoras_de_equipos_ciclistas
4                7             Wikipedia:Artículos_con_datos_locales
...            ...                                                ...
13308614  10010781                                    Nacidos_en_1994
13308615  10010781                                     Personas_vivas
13308616  10010783                          Fundaciones_en_Sudáfrica
13308617  10010787                 Fundaciones_en_Sudáfrica_por_año
13308618  10010787                                 Sudáfrica_en_2010

[13308619 rows x 2 columns]

Realizo un merge de los dos dataFrames para tener toda la información necesaria en un único dataFrame.

In [21]:
dfMerge = arcCat.merge(arcGeo)
dfMerge

id                                          categoria  \
0               7                                            Andorra   
1               7  Instituciones_patrocinadoras_de_equipos_ciclistas   
2               7             Wikipedia:Artículos_con_datos_locales   
3               7  Wikipedia:Artículos_con_datos_por_trasladar_a...   
4               7    Wikipedia:Artículos_con_enlaces_externos_rotos   
...           ...                                                ...   
3042005  10010690  Wikipedia:Artículos_con_datos_por_trasladar_a...   
3042006  10010690      Wikipedia:Artículos_con_ficha_sin_actualizar   
3042007  10010690  Wikipedia:Artículos_sin_imagen_en_entidad_sub...   
3042008  10010724                       Ríos_de_Nueva_Gales_del_Sur   
3042009  10010724   Wikipedia:Artículos_con_coordenadas_en_Wikidata   

            gt_lat      gt_lon  
0        42.500000    1.500000  
1        42.500000    1.500000  
2        42.500000    1.500000  
3        42.500000    1.500000  
4        42.500000    1.500000  
...            ...         ...  
3042005  23.000000   91.730000  
3042006  23.000000   91.730000  
3042007  23.000000   91.730000  
3042008 -30.931944  147.628889  
3042009 -30.931944  147.628889  

[3042010 rows x 4 columns]

Libero el espacio que me estan ocupando en RAM los dos dataFrames que no utilizare.

In [22]:
del arcCat

In [23]:
del arcGeo

In [24]:
#Verifico cual es el tipo de datos que estoy manejando
dfMerge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3042010 entries, 0 to 3042009
Data columns (total 4 columns):
 #   Column     Dtype  
---  ------     -----  
 0   id         int64  
 1   categoria  object 
 2   gt_lat     float64
 3   gt_lon     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 116.0+ MB


Verifico si mi DataFrame tiene nulos.

In [25]:
dfMerge.isnull().sum()

id           0
categoria    0
gt_lat       0
gt_lon       0
dtype: int64

El DataFrame esta listo para ser utilizado

Agrupo por categorias para hallar la latitud y longitud promedio de cada una.

In [27]:
dfGrouped = dfMerge.groupby('categoria').agg({'gt_lat' : 'mean', 'gt_lon' : 'mean'})
dfGrouped

gt_lat     gt_lon
categoria                                  
1._FC_Colonia          50.933611   6.875000
1._FC_Heidenheim_1846  48.668500  10.139300
1._FC_Kaiserslautern   49.434444   7.775833
1._FC_Nürnberg        49.426389  11.125278
1._FC_Union_Berlin     52.457222  13.568056
...                          ...        ...
Å koda                 50.421100  14.930600
Żagań                51.616667  15.316667
Żnin                  52.849580  17.719920
Żywiec                49.688633  19.204017
Žilina                49.225833  18.708125

[108042 rows x 2 columns]

In [28]:
del dfMerge

In [30]:
dfGrouped[['gt_lat', 'gt_lon']].values

array([[50.933611  ,  6.875     ],
       [48.6685    , 10.1393    ],
       [49.434444  ,  7.775833  ],
       ...,
       [52.84958   , 17.71992   ],
       [49.68863333, 19.20401667],
       [49.22583342, 18.70812508]])

In [31]:
type(dfGrouped[['gt_lat', 'gt_lon']].values)

numpy.ndarray

Utilizo NarestNeighbors para hallar las catagorias mas cercanas. Buscare los dos vecinos mas cercanos de cada una, ya que el primer vecino (el mas proximo) sera la misma categoria.

In [32]:
cercania = NearestNeighbors(n_neighbors=2, algorithm='brute').fit(dfGrouped[['gt_lat', 'gt_lon']].values)
distances, indices = cercania.kneighbors(dfGrouped[['gt_lat', 'gt_lon']].values)

In [33]:
distances

array([[0.        , 0.00644806],
       [0.        , 0.01694943],
       [0.        , 0.        ],
       ...,
       [0.        , 0.0660249 ],
       [0.        , 0.05390422],
       [0.        , 0.03146806]])

Me quedo con las distancias de cada categoria a su (segunda) categoria más cercana.

In [34]:
distancias = distances[:,1].flatten()
distancias

array([0.00644806, 0.01694943, 0.        , ..., 0.0660249 , 0.05390422,
       0.03146806])

Veo cual es la mínima distancia.

In [35]:
np.amin(distancias, axis=None, out=None, initial=None)

0.0

Veo cuales son los que me generan la minima distancia.

In [36]:
np.where(distancias == np.amin(distancias))

(array([     2,      5,     13, ..., 108008, 108010, 108014], dtype=int64),)

Busco las categorias

In [37]:
indices[:,1].flatten()

array([ 30986,  10951,  30997, ...,   6588, 105397,  91688], dtype=int64)

Se cumplen varios casos en los que la distancia minima es 0, por lo que tomare el segundo caso. Es decir, la posicion 5 de los vectores.

In [38]:
print('pos_cat 1: ',indices[5][0],'pos_cat 2: ',indices[5][1])

pos_cat 1:  5 pos_cat 2:  31504


Busco la informacion en mi dataFrame orginal de las dos categorias que son mas cercanas.

In [39]:
df.iloc[indices[5][0], :]

gt_lat    49.992500
gt_lon     8.234862
Name: 1._FSV_Maguncia_05, dtype: float64

In [40]:
df.iloc[indices[5][1], :]

gt_lat    49.992500
gt_lon     8.234862
Name: Deporte_en_Maguncia, dtype: float64

#### Respuesta

In [41]:
print('Por lo tanto, las dos categorias más cercanas son: ',df.iloc[indices[5][0], :].name , 'y ', df.iloc[indices[5][1], :].name )

Por lo tanto, las dos categorias más cercanas son:  1._FSV_Maguncia_05 y  Deporte_en_Maguncia
